<?php
   return [
      'currency' => 'IDR',
      'inv_purchase_receive' => 99,
      'inv_consumption' => 98,
      'inv_return_purchase' => 97,
      'inv_return_consumption' => 96,
      'inv_receive_sample' => 95,
      'inv_units' => [
         'BH',
         'PCS',
         'MTR',
         'CM',
         'KG',
         'TON',
         'SET',
         'PSG',
         'LTR',
         'DRUM',
         'PAIL',
         'BTL',
         'BTG',
         'INCI',
         'KAKI',
         'MM',
         'GRM',
         'LSN',
         'LBR',
         'UNIT',
         'DUS',
         'KOTAK',
         'RIM',
         'BLOK',
         'PAPAN',
      ],
   ];

